spring.application.name=erp_new_app_3

erpnext.api.url=http://erpnext.localhost:8000
erpnext.api.key=5f181ae87a9a36e
erpnext.api.secret=28bf325624a07c5

spring.datasource.url=jdbc:mariadb://localhost:3306/_669fe6202f021125
spring.datasource.username=root
spring.datasource.password=Lucio1328
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.web.resources.static-locations=classpath:/static/
